kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: jackett
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/fleet-namespace-test.git
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
  paths:
  - ./namespaces/helm