{{- range $v := .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: "feebar"
  labels:
    field.cattle.io/projectId: "foobar""
  name: {{ $v.namespace }}
---
{{- end }}